# Generated by Django 5.2 on 2025-09-07 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok_data', '0011_remove_folder_tiktok_data_scrape__71a579_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(help_text='The text content of the comment')),
                ('user_name', models.CharField(help_text='Username of the commenter', max_length=100)),
                ('user_id', models.CharField(blank=True, help_text='User ID of the commenter', max_length=100, null=True)),
                ('user_url', models.URLField(blank=True, help_text='Profile URL of the commenter', max_length=500, null=True)),
                ('num_likes', models.IntegerField(default=0, help_text='Number of likes on this comment')),
                ('num_replies', models.IntegerField(default=0, help_text='Number of replies to this comment')),
                ('comment_id', models.CharField(help_text='Unique identifier for this comment', max_length=100)),
                ('post_id', models.CharField(help_text='ID of the post this comment belongs to', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_date', models.DateTimeField(blank=True, help_text='Date when the comment was posted', null=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tiktok_data.folder')),
                ('tiktok_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tiktok_data.tiktokpost')),
            ],
            options={
                'verbose_name': 'TikTok Comment',
                'verbose_name_plural': 'TikTok Comments',
                'ordering': ['-comment_date', '-created_at'],
                'indexes': [models.Index(fields=['user_name'], name='tiktok_data_user_na_ee65bd_idx'), models.Index(fields=['comment_id'], name='tiktok_data_comment_429e0d_idx'), models.Index(fields=['post_id'], name='tiktok_data_post_id_4849a1_idx'), models.Index(fields=['comment_date'], name='tiktok_data_comment_22c0d1_idx')],
                'unique_together': {('comment_id', 'post_id')},
            },
        ),
    ]
