name: track-futura
type: python:3.11

# Build configuration
build:
  flavor: none

# Web configuration
web:
  commands:
    start: gunicorn --bind 0.0.0.0:$PORT --workers 3 config.wsgi:application
  upstream:
    socket_family: tcp
    protocol: http
  locations:
    "/":
      root: "public"
      index: ["index.html"]
      allow: true
      passthru: true
    "/api/":
      passthru: true
    "/admin/":
      passthru: true
    "/static/":
      passthru: true

# Variables
variables:
  env:
    # Django configuration
    DJANGO_SETTINGS_MODULE: config.settings_production
    PYTHONPATH: /app/backend
    DEBUG: false
    DJANGO_ALLOWED_HOSTS: "*"

    # OpenAI API Key (set this in platform environment variables)
    OPENAI_API_KEY: "${OPENAI_API_KEY}"

    # BrightData configuration
    BRIGHTDATA_WEBHOOK_TOKEN: "8af6995e-3baa-4b69-9df7-8d7671e621eb"
    BRIGHTDATA_BASE_URL: "https://trackfutura.futureobjects.io"

    # Email configuration (optional)
    EMAIL_HOST: "smtp.gmail.com"
    EMAIL_PORT: "587"
    EMAIL_USE_TLS: "true"
    EMAIL_HOST_USER: ""
    EMAIL_HOST_PASSWORD: ""
    DEFAULT_FROM_EMAIL: ""

    # Webhook configuration
    WEBHOOK_RATE_LIMIT: "100"
    WEBHOOK_MAX_TIMESTAMP_AGE: "300"
    WEBHOOK_MAX_EVENTS: "1000"
    WEBHOOK_METRICS_RETENTION: "3600"
    WEBHOOK_ERROR_THRESHOLD: "0.1"
    WEBHOOK_RESPONSE_TIME_THRESHOLD: "5.0"
    WEBHOOK_ENABLE_CERT_PINNING: "false"

# Mounts
mounts:
  static: /app/backend/staticfiles

# Relationships
relationships:
  database: postgresql:postgresql

# Hooks
hooks:
  build: |
    cd /app/backend
    pip install -r requirements.txt
    python manage.py collectstatic --noinput --clear
  deploy: |
    cd /app/backend
    python manage.py migrate --noinput

# Source directory
source:
  root: backend