"https://{default}/":
  type: upstream
  upstream: track-futura:http

"https://{default}/api/":
  type: upstream
  upstream: track-futura:http
  cache:
    enabled: false

"https://{default}/admin/":
  type: upstream
  upstream: track-futura:http

"https://{default}/static/":
  type: upstream
  upstream: track-futura:http
