# Generated by Django 5.2 on 2025-09-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_remove_webhook_status_field'),
    ]

    operations = [
    ]
