# Generated by Django 5.2 on 2025-09-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_auto_20250904_1548'),
    ]

    operations = [
    ]
